/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/components/App.vue')['default']
    BasicLayout: typeof import('./src/components/layouts/BasicLayout.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Index: typeof import('./src/components/pages/Index.vue')['default']
    Indexx: typeof import('./src/components/pages/Indexx.vue')['default']
    Team: typeof import('./src/components/pages/Team.vue')['default']
  }
}
